# Generated by Django 3.1.12 on 2024-11-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
