# Generated by Django 3.1.12 on 2024-11-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruta',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
